agent-model-name: llama3-groq-70b-8192-tool-use-preview
error-model-name: llama-3.1-70b-versatile

database:
    host: localhost
    user: root
    password: 
    database: db
    table: mytable

google-firestore:
    PROJECT_ID: appointment-schedule-manager
    SESSION_ID: user1_session_new
    COLLECTION_NAME: chat_history

whatsapp-bot-number: whatsapp:+14155238886
